language: php

php: 
  - 7.2
  - 7.3
  - 7.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - find -L . ! -path "*/vendor/*" -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  - vendor/bin/phpunit
